[package]
name = "wsq"
version = "0.1.0"
authors = ["Yushi OMOTE <yushiomote@gmail.com>"]
edition = "2018"

[dependencies]
ws = "0.9"
serde = "1"
serde_json = "1"
log = "0.4"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
